mutation createProduct(
  $name: String!
  $description: String
  $type: String
  $price: Int
  $stock: Int
  $img: String
  $time: String
  $category: String
) {
  createProduct(
    name: $name
    description: $description
    type: $type
    price: $price
    stock: $stock
    img: $img
    time: $time
    category: $category
  ) {
    id
    name
    description
    slug
    type
    price
    stock
    img
    time
    category{
      id
      name
      slug
      img
    }
    vendor {
      id
      firstName
      lastName
      phone
      info {
        restaurant
      }
    }
  }
}
