mutation createProduct(
  $name: String!
  $description: String
  $type: String
  $rate: Int
  $stock: Int
  $img: String
  $time: String
) {
  createProduct(
    name: $name
    description: $description
    type: $type
    rate: $rate
    stock: $stock
    img: $img
    time: $time
  ) {
    id
    name
    description
    slug
    type
    rate
    stock
    img
    time
    vendor {
      id
      firstName
      lastName
      phone
      info {
        restaurant
      }
    }
  }
}
