query Products {
  products {
    id
    slug
    name
    type
    rate
    qty
    img
    time
    vendor{
      id
      firstName
      lastName
      phone
      email
      info{
        restaurant
        kitchenPhotos
      }
    }
  }
}