query Product($id: ID!) {
  product(id: $id) {
    id
    slug
    name
    description
    type
    rate
    stock
    img
    time
    vendor {
      id
      firstName
      lastName
      phone
      email
      info {
        restaurant
        kitchenPhotos
      }
    }
  }
}
