query Products {
  products {
    id
    slug
    name
    type
    price
    stock
    img
    time
    category{
      id
      name
      slug
      img
    }
    vendor {
      id
      firstName
      lastName
      phone
      email
      info {
        restaurant
        kitchenPhotos
      }
    }
  }
}
