mutation updateProduct(
  $id: ID!
  $name: String!
  $description: String
  $type: String
  $price: Int
  $stock: Int
  $img: String
  $time: String
) {
  updateProduct(
    id: $id
    name: $name
    description: $description
    type: $type
    price: $price
    stock: $stock
    img: $img
    time: $time
  ) {
    id
    name
    description
    slug
    type
    price
    stock
    img
    time
    vendor {
      id
      firstName
      lastName
      phone
      info {
        restaurant
      }
    }
  }
}
