query me {
  me {
    id
    firstName
    lastName
    phone
    role
    verified
    active
    avatar
    address {
      address
      town
      city
      state
      zip
    }
    info {
      public
      restaurant
      kitchenPhotos
    }
  }
}
