mutation updateProfile(
  $address: AddressInput
  $firstName: String
  $lastName: String
  $avatar: String
  $dob: String
  $gender: String
  # $state: String
  # $city: String
  $phone: String
  $info: InputInfo
) {
  updateProfile(
    firstName: $firstName
    lastName: $lastName
    avatar: $avatar
    phone: $phone
    dob: $dob
    gender: $gender
    info: $info
    address: $address
  ) {
    firstName
    lastName
    avatar
    address {
      address
      town
      city
      state
      zip
    }
    info {
      public
      restaurant
      kitchenPhotos
    }
  }
}
