mutation updateAddress(
  $id: ID!
  $email: String
  $firstName: String
  $lastName: String
  $address: String
  $town: String
  $city: String
  $country: String
  $state: String
  $zip: Int
  $phone: String
) {
  updateAddress(
    id: $id
    email: $email
    firstName: $firstName
    lastName: $lastName
    address: $address
    town: $town
    city: $city
    country: $country
    state: $state
    zip: $zip
    phone: $phone
  ) {
    id
    firstName
    lastName
    address
    town
    city
    country
    state
    coords {
      lat
      lng
    }
    zip
    phone
    active
    createdAt
    updatedAt
  }
}
