query todayTotal {
  todayTotal {
    id
    orderNo
    otp
    amount {
      qty
      subtotal
      total
      shipping
      discount
    }
    payment_order_id
    delivery {
      otp
      finish {
        lat
        lng
      }
    }
    status
    items {
      name
      slug
      img
      price
      qty
    }
    address {
      firstName
      lastName
      address
      town
      city
      zip
      coords {
        lat
        lng
      }
    }
    createdAt
    updatedAt
  }
}
